apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-EKS-course-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    #instanceType: t2.small
    instanceType: t2.micro
    desiredCapacity: 3
    #ssh: # use existing EC2 key
      #publicKeyName: eks-course
      #publicKeyName: console-ssh-key-pair.pem