apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployments
  labels: 
    app: my-deployments-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: my-nginx-container
        image: nginx