apiVersion: v1 
kind: ResourceQuota 
metadata: 
  name: pods-medium 
spec: 
  hard: 
    cpu: "10" 
    memory: 20Gi 
    pods: "10" 
  scopeSelector: 
    matchExpressions: 
      - operator : In 
        scopeName: PriorityClass 
        values: ["medium"]