apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-newprobe
  name: my-newprobe
spec:
  containers:
  - image: nginx
    name: my-newprobe
    resources: {}
    livenessProbe:
      exec:
        command:
          - "!bin/sh"
          - -c
          - "touch /tmp/mylife; 3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
