apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - image: nginx
        name: nginx
