apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 32001
  selector:
    app: my-service
  type: NodePort
