apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-service
  name: my-fix
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-fix
  template:
    metadata:
      labels:
        run: my-fix
    spec:
      containers:
      - image: nginx
        name: my-service
---
apiVersion: v1
kind: Service
metadata:
  name: fix-service
  labels:
    run: fix-service
spec:

  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: my-fix