apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-quota
  name: my-quota
spec:
  containers:
  - image: nginx
    name: my-quota
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 512Mi
        cpu: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
