spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
      - name: DB_PASSWORD
        valueFrom:
           secretRefKey:
              name: mysecret
              value: DB_PASSWORD_KEY