apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-security-context
  name: pod-security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - image: busybox
    name: pod-security-context
    resources: {}
    command: ["sh", "-c", "sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {} 
