apiVersion: v1
kind: Pod
metadata:
  labels:
    run: request-resources
  name: request-resources
spec:
  containers:
  - image: nginx
    name: request-resources
    resources:
      request:
        cpu: 0.2
        memory: 100Mi

      limits:
        cpu: 1
        memory: 200Mi
