apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness
  name: liveness
spec:
  containers:
  - image: ubuntu
    name: liveness
    resources: {}
    livenessProbe:
      exec:
        command:
          - service
          - status
          - nginx
      initialDelaySeconds: 20
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
