apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-logs
  name: pod-logs
spec:
  containers:
  - image: busybox
    name: pod-logs
    resources: {}
    command:
      - "ping"
      - "google.com"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
